"""extend professor with course, area, lattes, nde fields

Revision ID: 46fd59ba203e
Revises: baf2dda29b21
Create Date: 2026-07-03 02:52:29.557118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fd59ba203e'
down_revision: Union[str, Sequence[str], None] = 'baf2dda29b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('email_secondary', sa.String(length=200), nullable=True))
    op.add_column('professors', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('professors', sa.Column('area', sa.String(length=300), nullable=True))
    op.add_column('professors', sa.Column('lattes_url', sa.String(length=300), nullable=True))
    op.add_column('professors', sa.Column('personal_site_url', sa.String(length=300), nullable=True))
    op.add_column('professors', sa.Column('is_nde', sa.Boolean(), nullable=False))
    op.add_column('professors', sa.Column('nde_role', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'professors', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professors', type_='foreignkey')
    op.drop_column('professors', 'nde_role')
    op.drop_column('professors', 'is_nde')
    op.drop_column('professors', 'personal_site_url')
    op.drop_column('professors', 'lattes_url')
    op.drop_column('professors', 'area')
    op.drop_column('professors', 'course_id')
    op.drop_column('professors', 'email_secondary')
    # ### end Alembic commands ###
