"""add professor degree and discipline prerequisites_text

Revision ID: f2e2465557bd
Revises: 46fd59ba203e
Create Date: 2026-07-03 06:42:21.652671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e2465557bd'
down_revision: Union[str, Sequence[str], None] = '46fd59ba203e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('prerequisites_text', sa.String(length=300), nullable=True))
    op.add_column('professors', sa.Column('degree', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professors', 'degree')
    op.drop_column('disciplines', 'prerequisites_text')
    # ### end Alembic commands ###
